# Generated by Django 2.0.7 on 2018-07-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('species', '0001_initial'),
        ('transport', '0001_initial'),
        ('planet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('episode_id', models.IntegerField()),
                ('opening_crawl', models.TextField(max_length=1000)),
                ('director', models.CharField(max_length=100)),
                ('producer', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('characters', models.ManyToManyField(blank=True, related_name='films', to='people.People')),
                ('planets', models.ManyToManyField(blank=True, related_name='films', to='planet.Planet')),
                ('species', models.ManyToManyField(blank=True, related_name='films', to='species.Species')),
                ('starships', models.ManyToManyField(blank=True, related_name='films', to='transport.Starship')),
                ('vehicles', models.ManyToManyField(blank=True, related_name='films', to='transport.Vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
